import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import { MyNextUiProvider } from "@/utils/MyNextUiProvider";
import { FloatingSocial } from "./components";
import Footer from "./Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Century Premiere Suite",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyNextUiProvider>
          <NavBar />
          <FloatingSocial />
          <main>{children}</main>
          <Footer />
        </MyNextUiProvider>
      </body>
    </html>
  );
}
